cloud:
  aws:
    s3:
      bucket: miniproject12storage
    credentials:
      accessKey: AKIAWQSK4KZWBTXHXA5E
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false