server:
  error:
    whitelabel:
      enabled: false
  port: 5000
  servlet:
    encoding:
      charset: utf-8
      force: true
  tomcat:
    connection-timeout: -1

logging:
  level:
    '[com.fastcampus.minischeduler]': INFO
    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
cloud:
  aws:
    s3:
      bucket: ${S3.BUCKET}
    credentials:
      accessKey: ${S3.ACCESS.KEY}
      secretKey: ${S3.SECRET.KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

my-env:
  jwt:
    secret: ${JWT.SECRET}
  aes256:
    iv: ${AES256.IV}
    key: ${AES256.KEY}
    alg: ${AES256.ALG}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  datasource:
    username: ${RDS.USERNAME}
    password: ${RDS.PASSWORD}
    url: jdbc:mysql://${RDS.HOSTNAME}:${RDS.PORT}/${RDS.DB.NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  devtools:
    livereload:
      enabled: true
  profiles:
    active: aws