
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
logging:
  level:
    '[com.fastcampus.minischeduler]': DEBUG
    '[org.hibernate.type]': TRACE
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

my-env:
  jwt:
    secret: ${JWT_SECRET}
  aes256:
    iv: ${AES256_IV}
    key: ${AES256_KEY}
    alg: ${AES256_ALG}

spring:
  datasource:
    username: ${DB_ID}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/minischeduler
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:templates
    suffix: .html
    mode: HTML
    check-template-location: true
    cache: false

file:
  dir: /Users/kilminjun/mini/scheduler/src/main/resources/static/asset/upload/